<#
.SYNOPSIS
  Scaffolds the FrontendForge output folder: 15 empty deliverable files under plan/, and a UIUX/ folder skeleton for the Phase 5b static reference site.

.PARAMETER ProjectName
  The project name (used as the output subfolder).

.PARAMETER Root
  Base directory for generated plans. Defaults to Next/Project relative to the workspace root.

.EXAMPLE
  ./scaffold-output.ps1 -ProjectName "TaskPulse"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectName,

    [string]$Root = (Join-Path (Get-Location) "Next/Project")
)

$ErrorActionPreference = "Stop"

$projectDir = Join-Path $Root $ProjectName
$planDir = Join-Path $projectDir "plan"
$uiuxDir = Join-Path $projectDir "UIUX"
$uiuxAssetsDir = Join-Path $uiuxDir "assets"
New-Item -ItemType Directory -Force -Path $planDir, $uiuxDir, $uiuxAssetsDir | Out-Null

$deliverables = @(
    "00-INDEX.md",
    "01-Project-Research.md",
    "02-Tech-Stack.md",
    "03-Architecture.md",
    "04-Product-Spec.md",
    "05-UIUX-Design.md",
    "06-Delivery-Plan.md",
    "07-Security-Auth.md",
    "08-Testing-Strategy.md",
    "09-Performance.md",
    "10-Internationalization.md",
    "11-Coding-Standards.md",
    "12-Starter-Template.md",
    "13-AI-Features.md",
    "14-Production-Deployment.md"
)

foreach ($file in $deliverables) {
    $path = Join-Path $planDir $file
    if (-not (Test-Path $path)) {
        $title = ($file -replace '\.md$', '') -replace '^\d+-', ''
        Set-Content -Path $path -Value "# $title`n`n> TODO: generated by FrontendForge.`n" -Encoding utf8
    }
}

$uiuxStubs = @{
    'README.md'          = "# $ProjectName UI/UX Reference`n`n> TODO: generated by FrontendForge Phase 5b.`n"
    'index.html'         = "<!doctype html><html><body><!-- TODO: FrontendForge Phase 5b will replace this with the landing page --></body></html>`n"
    'assets/tokens.css'  = "/* TODO: FrontendForge Phase 5b will write design tokens from 05-UIUX-Design.md */`n"
    'assets/app.js'      = "// TODO: FrontendForge Phase 5b will write shared JS (theme toggle, streaming demo, cmd palette).`n"
}
foreach ($rel in $uiuxStubs.Keys) {
    $path = Join-Path $uiuxDir $rel
    $dir = Split-Path $path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    if (-not (Test-Path $path)) { Set-Content -Path $path -Value $uiuxStubs[$rel] -Encoding utf8 }
}

Write-Host "Scaffolded $($deliverables.Count) deliverables in: $planDir"
Write-Host "Scaffolded UIUX reference skeleton in: $uiuxDir"
