<#
.SYNOPSIS
  Scaffolds the FrontendForge output folder and 14 empty deliverable files for a new project run.

.PARAMETER ProjectName
  The project name (used as the output subfolder).

.PARAMETER Root
  Base directory for generated plans. Defaults to Next/Project relative to the workspace root.

.EXAMPLE
  ./scaffold-output.ps1 -ProjectName "TaskPulse"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectName,

    [string]$Root = (Join-Path (Get-Location) "Next/Project")
)

$ErrorActionPreference = "Stop"

$planDir = Join-Path (Join-Path $Root $ProjectName) "plan"
New-Item -ItemType Directory -Force -Path $planDir | Out-Null

$deliverables = @(
    "00-INDEX.md",
    "01-Project-Research.md",
    "02-Tech-Stack.md",
    "03-Architecture.md",
    "04-Product-Spec.md",
    "05-UIUX-Design.md",
    "06-Delivery-Plan.md",
    "07-Security-Auth.md",
    "08-Testing-Strategy.md",
    "09-Performance.md",
    "10-Internationalization.md",
    "11-Coding-Standards.md",
    "12-Starter-Template.md",
    "13-AI-Features.md"
)

foreach ($file in $deliverables) {
    $path = Join-Path $planDir $file
    if (-not (Test-Path $path)) {
        $title = ($file -replace '\.md$', '') -replace '^\d+-', ''
        Set-Content -Path $path -Value "# $title`n`n> TODO: generated by FrontendForge.`n" -Encoding utf8
    }
}

Write-Host "Scaffolded $($deliverables.Count) deliverables in: $planDir"
